# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dotnet-microsoft:
        patterns:
          - "Microsoft.*"
      dotnet-system:
        patterns:
          - "System.*"

  - package-ecosystem: npm
    directory: "/ui"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      ui-production:
        dependency-type: production
      ui-development:
        dependency-type: development

  - package-ecosystem: npm
    directory: "/tests/e2e"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      e2e-all:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
