// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shortboxerr.Infrastructure.Persistence;

#nullable disable

namespace Shortboxerr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShortboxerrDbContext))]
    [Migration("20260202042727_AddProviders")]
    partial class AddProviders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Shortboxerr.Core.Entities.EditionContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EditionTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("IssueNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("EditionTitleId", "SortOrder");

                    b.ToTable("EditionContents", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.EditionTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EditionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Isbn");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Title");

                    b.ToTable("EditionTitles", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.FileAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EditionTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EditionTitleId")
                        .IsUnique();

                    b.HasIndex("Hash");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("FileAssets", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.HistoryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EditionTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EditionTitleId");

                    b.HasIndex("EventType");

                    b.HasIndex("IssueId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Timestamp");

                    b.ToTable("HistoryEvents", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFile")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IssueNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SatisfiedByEdition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "IssueNumber");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.ProviderDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Implementation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastHealthStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Settings")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.HasIndex("Category", "Priority");

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.HasIndex("ExternalSource", "ExternalId");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.EditionContent", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.EditionTitle", "EditionTitle")
                        .WithMany("Contents")
                        .HasForeignKey("EditionTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shortboxerr.Core.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EditionTitle");

                    b.Navigation("Issue");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.EditionTitle", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.Series", "Series")
                        .WithMany("Editions")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.FileAsset", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.EditionTitle", "EditionTitle")
                        .WithOne("File")
                        .HasForeignKey("Shortboxerr.Core.Entities.FileAsset", "EditionTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithOne("File")
                        .HasForeignKey("Shortboxerr.Core.Entities.FileAsset", "IssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EditionTitle");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.HistoryEvent", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.EditionTitle", "EditionTitle")
                        .WithMany()
                        .HasForeignKey("EditionTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shortboxerr.Core.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EditionTitle");

                    b.Navigation("Issue");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Issue", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.Series", "Series")
                        .WithMany("Issues")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.EditionTitle", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Issue", b =>
                {
                    b.Navigation("File");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Series", b =>
                {
                    b.Navigation("Editions");

                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
