// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shortboxerr.Infrastructure.Persistence;

#nullable disable

namespace Shortboxerr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShortboxerrDbContext))]
    [Migration("20260225224248_AddDownloadHistory")]
    partial class AddDownloadHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Shortboxerr.Core.Entities.CachedDiscoveryWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CacheTier")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastRefreshed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("WeekStart")
                        .IsUnique();

                    b.ToTable("CachedDiscoveryWeeks", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.DownloadHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AverageSpeedBytesPerSecond")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSite")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("DownloadId");

                    b.HasIndex("IssueId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SourceType");

                    b.HasIndex("State");

                    b.ToTable("DownloadHistories", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.EditionContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EditionTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("IssueNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("EditionTitleId", "SortOrder");

                    b.ToTable("EditionContents", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.EditionTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComicVineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComicVineUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EditionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolumeNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Isbn");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Title");

                    b.ToTable("EditionTitles", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.FallbackCoverEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComicVineIssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComicVineVolumeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FallbackCoverUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FallbackSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FallbackCoverEntries");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.FileAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EditionTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EditionTitleId")
                        .IsUnique();

                    b.HasIndex("Hash");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("FileAssets", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.HistoryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EditionTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EditionTitleId");

                    b.HasIndex("EventType");

                    b.HasIndex("IssueId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Timestamp");

                    b.ToTable("HistoryEvents", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComicVineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComicVineUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CoverDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFile")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAnnual")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("IssueNumber")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueNumberText")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSearchError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSearchedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MetadataLastRefreshed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SatisfiedByEdition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StoreDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComicVineId");

                    b.HasIndex("SeriesId", "IsAnnual");

                    b.HasIndex("SeriesId", "IssueNumber");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.IssueCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComicVineCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComicVineUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueCharacters");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.IssueStoryArc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComicVineStoryArcId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComicVineUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComicVineStoryArcId");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueStoryArcs", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.IssueTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComicVineTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComicVineUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueTeams");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.MetadataRefreshEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MetadataChanged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewIssuesDiscovered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedFieldsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MetadataRefreshEvents");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("IssueId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Type");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.PendingMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CandidatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedComicVineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PendingMatches");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.ProviderDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Implementation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastHealthStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Settings")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.HasIndex("Category", "Priority");

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aliases")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComicVineId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ComicVineLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComicVinePublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComicVineUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MetadataLastRefreshed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitoringMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalIssueCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComicVineId");

                    b.HasIndex("ParentSeriesId");

                    b.HasIndex("Title");

                    b.HasIndex("ExternalSource", "ExternalId");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.VariantCoverEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ComicVineImageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageTags")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimaryCover")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComicVineImageId");

                    b.HasIndex("IssueId");

                    b.HasIndex("IssueId", "IsPreferred");

                    b.ToTable("VariantCovers", (string)null);
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.DownloadHistory", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shortboxerr.Core.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Issue");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.EditionContent", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.EditionTitle", "EditionTitle")
                        .WithMany("Contents")
                        .HasForeignKey("EditionTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shortboxerr.Core.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EditionTitle");

                    b.Navigation("Issue");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.EditionTitle", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.Series", "Series")
                        .WithMany("Editions")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.FileAsset", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.EditionTitle", "EditionTitle")
                        .WithOne("File")
                        .HasForeignKey("Shortboxerr.Core.Entities.FileAsset", "EditionTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithOne("File")
                        .HasForeignKey("Shortboxerr.Core.Entities.FileAsset", "IssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EditionTitle");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.HistoryEvent", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.EditionTitle", "EditionTitle")
                        .WithMany()
                        .HasForeignKey("EditionTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shortboxerr.Core.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EditionTitle");

                    b.Navigation("Issue");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Issue", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.Series", "Series")
                        .WithMany("Issues")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.IssueCharacter", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithMany("Characters")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.IssueStoryArc", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithMany("StoryArcs")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.IssueTeam", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithMany("Teams")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Notification", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shortboxerr.Core.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Issue");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Series", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.Series", "ParentSeries")
                        .WithMany("LinkedAnnualSeries")
                        .HasForeignKey("ParentSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentSeries");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.VariantCoverEntity", b =>
                {
                    b.HasOne("Shortboxerr.Core.Entities.Issue", "Issue")
                        .WithMany("VariantCovers")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.EditionTitle", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Issue", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("File");

                    b.Navigation("StoryArcs");

                    b.Navigation("Teams");

                    b.Navigation("VariantCovers");
                });

            modelBuilder.Entity("Shortboxerr.Core.Entities.Series", b =>
                {
                    b.Navigation("Editions");

                    b.Navigation("Issues");

                    b.Navigation("LinkedAnnualSeries");
                });
#pragma warning restore 612, 618
        }
    }
}
